### ISSUE TITLE
Time tracking outside the browser

### ISSUE THREAD

**Issue by ForumLiker** [Sav22999/limite#8]
Hello. Is it possible to make the add-on not take into account the time when the browser is inactive?
My browser is minimized, but the time tracking continues.

**Comment by Sav22999** [comment]
@ForumLiker Hi! Thanks for the feedback. You're right, I'll try to see and fix this 😄

**Comment by Sav22999** [comment]
@ForumLiker In the new release (2.0.1) you can find this and many new features!
